volumes:
  repotox_test_db:

services:
  repotox_test_db:
    build: .
    container_name: ${DB_CONTAINER_NAME}
    command:
      ['mongod', '--replSet', 'rs', '--keyFile', '/etc/secrets/openssl-db-key']
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - repotox_test_db:/data/db
