volumes:
  db:
services:
  db:
    image: mongo:4.4
    container_name: 'repotox_test_db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'root'
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - db:/data/db
